spring.application.name=SclMs_School_service
server.port=8083
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/sclMs?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update


