spring.application.name=SclMs_School_service
server.port=8083
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/sclMs?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s

# Redis Connection Pool
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=1000ms

# Logging
logging.level.com.example.apigateway=DEBUG
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.data.redis=DEBUG

# Resilience4j Rate Limiting
resilience4j.ratelimiter.limiters.default.limit-for-period=100
resilience4j.ratelimiter.limiters.default.limit-refresh-period=1m
resilience4j.ratelimiter.limiters.default.timeout-duration=1s

